wifi_ssid: "wifi SSID..."
wifi_password: "wifi password..."
Dialog3G_Decoder_API: "API key..."
Dialog3G_Decoder_OTA: "OTA key..."
Dialog3G_Decoder_BROKER: "mqtt ip..."
Dialog3G_Decoder_BROKER_USER: "mqtt user..."
Dialog3G_Decoder_BROKER_PASS: "mqtt pass..."
